### ISSUE TITLE
Vagrant SPK Doesn't handle .sandstorm deletion clearly.

### ISSUE THREAD

**Issue by simonv3** [sandstorm-io/vagrant-spk#103]
I fully accept 100% of the blame of this going wrong because I was impatient, but @paulproteus was really helpful and asked that I write this up, so here it is:

I started following [the tutorial](https://docs.sandstorm.io/en/latest/vagrant-spk/packaging-tutorial-meteor/) for packaging a Meteor app for sandstorm. My internet cut out halfway through `vagrant-spk up` (42%) and the download stopped. In a moment of impatience (without waiting for help) I thought I'd try again, so I ran `vagrant-spk up` again. 

This happened:
```
$ vagrant-spk up
Calling 'vagrant' 'up' in /Users/simon/src/quick-survey/.sandstorm
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x debian-jessie-disk1.vmdk: truncated gzip input
bsdtar: Error exit delayed from previous errors.

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'debian/jessie64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'debian/jessie64'
    default: URL: https://atlas.hashicorp.com/debian/jessie64
==> default: Adding box 'debian/jessie64' (v8.2.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.2.1/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP server doesn't seem to support byte ranges. Cannot resume.
Traceback (most recent call last):
  File "/usr/local/bin/vagrant-spk", line 587, in <module>
    main()
  File "/usr/local/bin/vagrant-spk", line 584, in main
    operation(args)
  File "/usr/local/bin/vagrant-spk", line 459, in bring_up_vm
    call_vagrant_command(sandstorm_dir, "up")
  File "/usr/local/bin/vagrant-spk", line 196, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1
```
Then I took matters in my own hands and removed the `.sandstorm` folder, because I naively thought that the virtual machine would be stored there I guess?

I then went through the process again - `vagrant-spk setupvm meteor`.

I then called `vagrant-spk up` again:

```
Calling 'vagrant' 'up' in /Users/simon/src/quick-survey/.sandstorm
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'debian/jessie64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'debian/jessie64'
    default: URL: https://atlas.hashicorp.com/debian/jessie64
==> default: Adding box 'debian/jessie64' (v8.2.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.2.1/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP server doesn't seem to support byte ranges. Cannot resume.
Traceback (most recent call last):
  File "/usr/local/bin/vagrant-spk", line 587, in <module>
    main()
  File "/usr/local/bin/vagrant-spk", line 584, in main
    operation(args)
  File "/usr/local/bin/vagrant-spk", line 459, in bring_up_vm
    call_vagrant_command(sandstorm_dir, "up")
  File "/usr/local/bin/vagrant-spk", line 196, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1
```

Then @paulproteus came to the rescue and suggested:

```
$ vagrant-spk destroy
Calling 'vagrant' 'destroy' '--force' in /Users/simon/src/quick-survey/.sandstorm
==> default: VM not created. Moving on...
```
And then again:
```
$ vagrant-spk up
Calling 'vagrant' 'up' in /Users/simon/src/quick-survey/.sandstorm
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'debian/jessie64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'debian/jessie64'
    default: URL: https://atlas.hashicorp.com/debian/jessie64
==> default: Adding box 'debian/jessie64' (v8.2.1) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/debian/boxes/jessie64/versions/8.2.1/providers/virtualbox.box
==> default: Box download is resuming from prior download progress
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

HTTP server doesn't seem to support byte ranges. Cannot resume.
Traceback (most recent call last):
  File "/usr/local/bin/vagrant-spk", line 587, in <module>
    main()
  File "/usr/local/bin/vagrant-spk", line 584, in main
    operation(args)
  File "/usr/local/bin/vagrant-spk", line 459, in bring_up_vm
    call_vagrant_command(sandstorm_dir, "up")
  File "/usr/local/bin/vagrant-spk", line 196, in call_vagrant_command
    return subprocess.check_call(command, cwd=sandstorm_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['vagrant', 'up']' returned non-zero exit status 1
```

I was then asked to remove `~/.vagrant.d/tmp` and now everything is installing again. 

In the future I'll try just cd-ing into .sandstorm and doing `vagrant provision`.

**Comment by paulproteus** [comment]
Thanks Simon for filing this. I'm hopeful that we can fix this smoothly in
the long run.
