### ISSUE TITLE
vagrant-spk enter-grain does not work on Windows

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#171]
The error message is

```
ERROR: Failed to load enter_grain binary.Traceback (most recent call last):
  File "<string>", line 1012, in <module>
  File "<string>", line 1009, in main
  File "<string>", line 714, in shell
RuntimeError: ERROR: This vagrant-spk bundle seems to be corrupt: bad checksum o
n enter_grain binary.
vagrant-spk returned -1
```

Tested on 164.

**Comment by ocdtrekkie** [comment]
Removing `  enter-grain` from the sha1 file:

`Looking for apps in dev mode...
Looking for grains...

Traceback (most recent call last):
  File "<string>", line 1012, in <module>
  File "<string>", line 1009, in main
  File "<string>", line 760, in shell
TypeError: 'file' object is not callable
vagrant-spk returned -1`

**Comment by paulproteus** [comment]
For me, later on: this diff should simulate the manual fiddling that Jake did.

```
paulproteus@slittingmill:~/projects/vagrant-spk$ git diff
diff --git a/vagrant-spk b/vagrant-spk
index 852c1a2..9b2499b 100755
--- a/vagrant-spk
+++ b/vagrant-spk
@@ -708,7 +708,9 @@ def shell(args):
         # accidentally corrupted. If it is the empty string, ignore it; this way, we can avoid
         # checksum errors while developing the binary.
         with open(os.path.join(CODE_DIR, 'helpers', 'enter_grain.sha1'), 'rb') as fd:
-            desired_checksum = fd.read().strip()
+            # The first thing in the file, if you split by spaces, is a hex value. There may be
+            # other text after it, namely the filename that was checksummed.
+            desired_checksum = fd.read().split(' ')[0].strip()
         found_checksum = hashlib.sha1(enter_grain_binary).hexdigest()
         if (desired_checksum and (desired_checksum != found_checksum)):
             raise RuntimeError("ERROR: This vagrant-spk bundle seems to be corrupt: bad checksum on enter_grain binary.")
```

**Comment by paulproteus** [comment]
Jake's "file is not callable" error would probably be fixed by the following patch:

```
diff --git a/vagrant-spk b/vagrant-spk
index 852c1a2..badeca8 100755
--- a/vagrant-spk
+++ b/vagrant-spk
@@ -757,7 +757,7 @@ def shell(args):
         try:
             supervisor_pid, ownership_check, grain_id, child_pid = line.split()
         except:
-            sys.stderr('Error parsing line: %s. Crashing.' % line)
+            sys.stderr.write('Error parsing line: %s. Crashing.' % line)
             raise
         if ownership_check == 'ownership-correct':
             supervisors.append({
```

note that the underlying issue - that vagrant-spk is unable to run its ridiculous shell script across `vagrant ssh` - is something that will take further debugging.

**Comment by ocdtrekkie** [comment]
New bug with new test:

```
Looking for apps in dev mode...
['vagrant', 'ssh', '-c', "pidof spk || echo no-spk;SANDSTORM_UID=$(id sandstorm
| sed -r s,[^0-9],_,g | sed -r s,_+,_,g | cut -d _ -f 2 ) ; for pid in $(pidof s
upervisor); do echo $pid $(cat /proc/$pid/status | grep -q 'Uid:.*'${SANDSTORM_U
ID} && echo ownership-correct || echo ownership-wrong) $(xargs -0 -n1 echo < /pr
oc/$pid/cmdline  | grep -v -- - | head -n2 | tail -n1) $(grep -l ^PPid:\\\\s*${p
id}$ /proc/*/status | head -n1  | sed -r s,/proc/,,g | sed -r s,/status,,) ; don
e"]
Looking for grains...

Error parsing line: 1971 ownership-correct WLKXhXNZLZM3wZneBSnaFP. Crashing.Trac
eback (most recent call last):
  File "<string>", line 1020, in <module>
  File "<string>", line 1017, in main
  File "<string>", line 766, in shell
ValueError: need more than 3 values to unpack
vagrant-spk returned -1
```

**Comment by ocdtrekkie** [comment]
Looks like your 2016-06-01.exe version worked for me:

```
Looking for apps in dev mode...
['vagrant', 'ssh', '-c', "pidof spk || echo no-spk;SANDSTORM_UID=$(id sandstorm
| sed -r s,[^0-9],_,g | sed -r s,_+,_,g | cut -d _ -f 2 ) ; for pid in $(pidof s
upervisor); do echo $pid $(cat /proc/$pid/status | grep -q 'Uid:.*'${SANDSTORM_U
ID} && echo ownership-correct || echo ownership-wrong) $(xargs -0 -n1 echo < /pr
oc/$pid/cmdline  | grep -v -- - | head -n2 | tail -n1) $(grep -E -l ^PPid:[[:bla
nk:]]*${pid}$ /proc/*/status | head -n1  | sed -r s,/proc/,,g | sed -r s,/status
,,) ; done"]
Looking for grains...

This will run a shell in the context of a grain. Here is a list of running
grains you can attach to. Press enter to choose the first one, or type the
number next to the grain ID to choose it.

1. WLKXhXNZLZM3wZneBSnaFP

Your choice: [1] 1
OK. Chosen grain ID WLKXhXNZLZM3wZneBSnaFP, whose child PID is 3038. Attaching..
.
Adding enter_grain program to the grain in /tmp/vagrant-spk/enter-grain...
Calling 'vagrant' 'ssh' '-c' 'cd /opt/app/.sandstorm && sudo /proc/3038/root/tmp
/vagrant-spk/enter-grain 3038' in S:\Projects\Github\php-app-to-package-for-sand
storm\.sandstorm
Attaching to process ID 3038...
I have no name!@sandbox:/$ ls
Vagrantfile         launcher.sh  run                           srv
bin                 lib          sandstorm-files.list          stack
boot                lib64        sandstorm-http-bridge         tmp
build.sh            lost+found   sandstorm-http-bridge-config  usr
dev                 media        sandstorm-manifest            var
etc                 mnt          sandstorm-pkgdef.capnp        vmlinuz
global-setup.sh     opt          sbin
host-dot-sandstorm  proc         service-config
initrd.img          root         setup.sh
I have no name!@sandbox:/$ var
bash: var: command not found
I have no name!@sandbox:/$ cd var
I have no name!@sandbox:/var$ ls
lib  log  number.txt  run
I have no name!@sandbox:/var$ echo number.txt
number.txt
I have no name!@sandbox:/var$
```
