### ISSUE TITLE
`enter-grain` doesn't work if Vagrant is run from a Git checkout

### ISSUE THREAD

**Issue by ndarilek** [sandstorm-io/vagrant-spk#197]
If Vagrant is installed from source using [these instructions](https://www.vagrantup.com/docs/installation/source.html), `enter-grain` fails with the following error:

```
Looking for apps in dev mode...
Looking for grains...

Error parsing line: Note that the installers are what ensure that Vagrant has all required. Crashing.Traceback (most recent call last):
  File "/home/nolan/bin/vagrant-spk", line 1028, in <module>
    main()
  File "/home/nolan/bin/vagrant-spk", line 1025, in main
    operation(args)
  File "/home/nolan/bin/vagrant-spk", line 774, in shell
    supervisor_pid, ownership_check, grain_id, child_pid = line.split()
ValueError: too many values to unpack
```

**Comment by abliss** [comment]
Anyone know whether this is still an issue?
