### ISSUE TITLE
enter-grain error on Windows

### ISSUE THREAD

**Issue by ocdtrekkie** [sandstorm-io/vagrant-spk#264]
I don't know what this means, but enter-grain did not work for me on my Windows machine.

```
PS C:\Users\ocdtr\Projects\Jupyter-Lab-Sandstorm> vagrant-spk enter-grain
Looking for apps in dev mode...
Looking for grains...

Error parsing line: 5037 ownership-correct c5Xv6FfWHKr9sGAbrP3hGd. Crashing.Traceback (most recent call last):
  File "<string>", line 1001, in <module>
  File "<string>", line 998, in main
  File "<string>", line 786, in shell
ValueError: need more than 3 values to unpack
vagrant-spk returned -1
```

**Comment by zenhack** [comment]
Looks like this line is returning something other than a 4-tuple:

https://github.com/sandstorm-io/vagrant-spk/blob/f5a82f76fe791d52fea1e30c027fcdfaa2722f02/vagrant-spk#L788

Maybe do some print debugging around there?

**Comment by ocdtrekkie** [comment]
Print debugging this on Windows is likely to be super difficult because packaging the EXE in the release script is a super pain in the rear. I probably should figure out how to set up a Python environment on my Windows PC such that I could play with the actual script file.

**Comment by ocdtrekkie** [comment]
It looks like `5037 ownership-correct c5Xv6FfWHKr9sGAbrP3hGd` is missing the child_pid though, since it's looking for that after the grain_id, which we can see in that string.
